# Generated by Django 5.0.7 on 2024-08-31 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_cursos_app', '0002_alter_curso_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cursos', to='registro_cursos_app.estudiante'),
        ),
    ]
