# Generated by Django 5.0.7 on 2024-08-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_cursos_app', '0003_alter_curso_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='region',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
